feat: add third party scanners page
huggingface/hub-docs pull request #1463
Opened 2024-10-21 15:38 UTC by McPatate

2024-10-21 15:40 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/hub/pr_1463). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-10-21 16:42 UTC, julien-c commented on docs/hub/security.md
> +- [3rd party scanners](./third-party-scanners)
```suggestion
- [3rd party scanners](./security-third-party-scanners)
```

2024-10-21 16:43 UTC, julien-c commented on docs/hub/third-party-scanners.md
> +# 3rd Party scanners
```suggestion
# Third-party scanners
```

2024-10-21 16:46 UTC, julien-c commented on docs/hub/security-third-party-scanners.md
> +As Hugging Face has become the de facto platform for model sharing, we’d like to protect the community from this, hence why we have developed tools like [picklescan](https://github.com/mmaitre314/pic
```suggestion
As Hugging Face has become a popular platform for model sharing, we’d like to protect the community from this, hence why we have developed tools like [picklescan](https://github.com/mmaitre314/picklescan) and why we integrate 3rd party scanners.
```

2024-10-21 16:47 UTC, julien-c commented on docs/hub/security-third-party-scanners.md
> +[Protect AI](https://protectai.com/)'s [Guardian](https://protectai.com/guardian) catches both pickle and Keras exploits. Guardian also benefits from reports sent in by their community of bounty [Hun
move that to the top

2024-10-21 16:48 UTC, julien-c commented on docs/hub/security-third-party-scanners.md
> +# Third-party scanners
```suggestion
# Third-party scanner: ProtectAI
```

2024-10-21 21:00 UTC, seanpmorgan requested changes

2024-10-22 10:07 UTC, julien-c commented on docs/hub/security-third-party-scanner-protect-ai.md
> +<!-- insert image of report -->
@McPatate

2024-10-22 12:07 UTC, julien-c approved these changes

2024-10-22 12:07 UTC, merged