Snippet for sklearn
huggingface/hub-docs pull request #341
Opened 2022-09-29 14:42 UTC by merveenoyan

Taking from https://github.com/huggingface/hub-docs/pull/314 (sorry I sometimes get confused working between repositories that I work on forks 😂)

2022-09-29 14:51 UTC, merveenoyan commented
I somehow can't pass config to ModelInfo properly in Models.ts.

```
const x: SetOptional<ModelInfoWithSiblings, "siblings"> = new ModelInfo({
			_id:                 repo._id,
			id:                  repo.name,
			author:              repo.author,
			sha:                 commit.id,
			lastModified:        commit.author.date,
			lastAuthor:          { email: commit.author.email },
			private:             repo.config.private,
			gated:               repo.config.gated,
			discussionsDisabled: repo.config.discussionsDisabled,
			gitalyUid:           repo.gitalyUid,
			files,
			config,
		});
console.log({ x });
console.log({ config });
```
config is still { config: { filename: 'model.pkl' } } but in ModelInfo it's {}. Do you have any idea?

2022-09-29 21:40 UTC, osanseviero commented
I'm not entirely sure to what does the code you're sharing correspond to. My workflow is to create a model repo with the same `README.md` and `config.json` as you would have in production, and within the `sklearn` method you can inspect the `model` by printing it. 

You're doing 
```
const skopsmodelFile = model.config.filename
```

But the model file should be within `model.sklearn`, as it's done for `adapter_transformers` and `speechbrain`. E.g. compare your internal code against
* https://github.com/huggingface/moon-landing/pull/4004/files#diff-70e0418cb1c6bf88268219ab03cc6b00d76364960e8ab99671c71bfeb8f78ff4R347-R352
* https://github.com/huggingface/moon-landing/pull/4004/files#diff-70e0418cb1c6bf88268219ab03cc6b00d76364960e8ab99671c71bfeb8f78ff4R359-R361

For debugging you can also add a `console.log(config)` in the internal PR to understand what's going on, but there you're fully overriding the config.

2022-09-30 13:02 UTC, osanseviero requested changes
This looks good! Thanks for working on it! I left some minor suggestions and improvement requests

2022-09-30 13:02 UTC, osanseviero commented on js/src/lib/interfaces/Libraries.ts
> +			)`;
The indentation for this looks off in the screenshot you shared

2022-10-03 12:46 UTC, osanseviero commented
Let me know if it's ready for another review (and remember to mark as solved if things are resolved)

2022-10-03 13:28 UTC, osanseviero commented on js/src/lib/interfaces/Libraries.ts
> +model = load(${skopsmodelFile})`;
Does copy pasting this snippet work? Should `load` also pass the folder where it was saved?

2022-10-04 12:39 UTC, merveenoyan commented
<img width="890" alt="Ekran Resmi 2022-10-04 14 38 49" src="https://user-images.githubusercontent.com/53175384/193821312-25759ef0-146c-4cb5-90c9-f1770ad6efab.png">
@osanseviero WDYT

2022-10-04 13:10 UTC, osanseviero commented on js/src/lib/interfaces/Libraries.ts
> +# if model is a pickle file, load with pickle at your own risk
```suggestion
# if model is a pickle file, make sure it's from a source you trust
```

2022-10-04 13:10 UTC, osanseviero approved these changes
Looks good! I just left a suggestion on the comment :fire: thanks!

2022-10-04 14:54 UTC, merged