DOI Documentation
huggingface/hub-docs pull request #390
Opened 2022-10-10 10:25 UTC by Kakulukian

I began to write the documentation for DOI generation.

Mainly based on the blogpost

2022-10-10 10:28 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/hub/pr_390). All of your documentation changes will be reflected on that endpoint.

2022-10-10 11:56 UTC, julien-c reviewed
looks good to me!

Will need to update the "DOI" section in repo settings to point to this doc, once it's up
Will need to update the blogpost to also point to this doc

Will need to link to the blogpost announcement from this doc

2022-10-10 13:01 UTC, Kakulukian commented
cc @sashavor @cakiki

2022-10-10 14:43 UTC, Kakulukian commented
Isn't it more like when the cookie expires? It seems to be done at logout

2022-10-10 15:54 UTC, mishig25 commented on docs/hub/doi.md
> +## Can I regenerate a new DOI if my model/dataset changes?
could you try replacing `model/dataset` with `model or dataset` here ?

2022-10-10 17:08 UTC, osanseviero approved these changes
The content looks good!

2022-10-11 09:15 UTC, cakiki requested changes

2022-10-11 09:15 UTC, cakiki commented on docs/hub/doi.md
> +## Why there is 'locked by DOI' message on delete, rename and change visibility action on my model or dataset?
Small nit: should be "Why is there"

2022-10-11 09:16 UTC, cakiki commented on docs/hub/doi.md
> +<img class="block dark:hidden" src="https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/hub/doi-generation.png"/>
Why is the "to" highlighted?

2022-10-11 09:51 UTC, merged

2022-10-11 09:51 UTC, Kakulukian commented
Thanks @cakiki 👍 
I merge it!