add code to languages list of datasets
huggingface/hub-docs pull request #439
Opened 2022-10-20 10:12 UTC by loubnabnl

Add `code` to the list of languages displayed on the Hub for datasets.

2022-10-20 10:46 UTC, osanseviero approved these changes
Looks good, thanks!

Although I do wonder if here we want to have a different tag for each programming language or a single one is fine. WDT?

cc @julien-c @lvwerra

2022-10-20 10:54 UTC, julien-c requested changes
I don't think adding `code` here will solve the original issue actually (can you link to the original issue? That can be an internal Slack link, that's fine)

2022-10-20 10:54 UTC, julien-c commented
this list is for human languages only

2022-10-20 10:57 UTC, osanseviero commented
https://huggingface.slack.com/archives/C02EMARJ65P/p1666255575685159

2022-10-20 10:57 UTC, osanseviero commented
We have 48 datasets with code tag https://huggingface.co/datasets?language=language:code but code is not showed in the language list.

2022-10-20 11:52 UTC, loubnabnl commented
It could be nice to have separate programming languages but not sure if it makes sense to mix them with natural languages, also the existing code datasets only have one code tag so maybe it's fine to just add `code`

2022-10-21 11:58 UTC, julien-c commented
Closing this PR in favor of a better fix in internal repo!

2022-10-21 11:58 UTC, closed without merging