Corrected 20 to 200, status code.
huggingface/hub-docs pull request #638
Opened 2023-01-25 19:50 UTC by ankitjaininfo

Also, added clarifications for local tunnels.

2023-01-25 19:53 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/hub/pr_638). All of your documentation changes will be reflected on that endpoint.

2023-01-26 13:52 UTC, julien-c requested changes
Are you affiliated with Beeceptor? 🤣

I would not mention them again in the second paragraph as i think ngrok and localtunnel are more well-known for this use case

2023-01-26 17:18 UTC, ankitjaininfo commented
No I am not affiliated. I love their product and simplicity. When I saw you have added a section about localhost routing, I thought to mention it. I am push a change to remove Beeceptor.

Notice that, there is another correction for 20 ==> 200 status code.

2023-01-26 19:36 UTC, julien-c approved these changes
looks good to me! thanks

2023-01-26 19:37 UTC, merged