Added about.md for image-to-text task
huggingface/hub-docs pull request #686
Opened 2023-02-20 07:39 UTC by hitchhiker3010

Partially fixes #352

2023-02-21 19:23 UTC, merveenoyan requested changes
Thanks a lot for working on this! I just did nitpicking, but we can merge and put it live this week. 
Also it would be nice if you could write your Hugging Face user ID so we could give you credits at the end of the page.

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +### Image Captioning
Can you write a small explanation on what below snippet is for? Same with OCR.

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +## Task Variants
I think this is not needed as of now 😊

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +OCR converts the text present in an image(Ex: Scanned document) to machine readable formats.
```suggestion
OCR models convert the text present in an image, e.g. a scanned document, to text.
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> + - For more details on this task refer [here](https://huggingface.co/docs/transformers/main/en/tasks/image_captioning)
```suggestion
```
This already exists in useful resources so I'd say we remove it

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +This can help the visually impaired to understand what's happening in their surroundings.
```suggestion
This can help the visually impaired people to understand what's happening in their surroundings.
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +
```suggestion
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +
```suggestion
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +
```suggestion
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +
```suggestion
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +
```suggestion
```

2023-02-21 19:23 UTC, merveenoyan commented on tasks/src/image-to-text/about.md
> +### OCR
Can below script be simplified? pinging @NielsRogge in case he has suggestions.

2023-02-22 06:21 UTC, hitchhiker3010 commented
Hi @merveenoyan 
I've made the changes as per your suggestions.
My Hugging Face user id is hitchhiker3010

2023-02-27 16:02 UTC, merveenoyan approved these changes
LGTM! Thanks a lot!

2023-02-27 16:02 UTC, merged